import Vuex from 'vuex'

const store = () => new Vuex.Store({
  state: {
    clientName: '',
    deliveryDate: '',
    siteName: '',
    siteDescription: '',
    ogpDescription: '',
    checkList: [],
    generation: [20, 40],
    gender: '男性',
    employment: '会社員',
    local: '都内',
    webPlatform: '静的サイト',
    checkDisplayPlatAll: false,
    displayPlatform: [
      { val: 'Android5.0〜' },
      { val: 'iOS9.0〜' },
      { val: 'Internet Explorer8.0〜' },
      { val: 'Opera' },
      { val: 'Edge' },
      { val: 'Safari' },
      { val: 'Firefox' },
      { val: 'Chrome' },
    ],
    checkedDisplayPlatform: [],
    isPlatIndeterminate: true,
    checkSupportedScopeAll: false,
    supportedScope: [
      { val: 'スマートフォン' },
      { val: 'タブレット' },
      { val: 'ノートPC' },
      { val: 'ラップトップ' },
    ],
    checkedSupportedScope: [],
    isScopeIndeterminate: true,
    referenceSite1: '',
    referenceSite2: '',
    referenceSite3: '',
    otherSiteImage: '',
    necessaryFunctional: '',
    images: '新規作成',
    collectionImageUrl: '',
    texts: '新規作成',
    collectionTextUrl: '',
    copyright: '',
    serverCompanyName: '',
    serverPassword: '',
    serverAdminLoginId: '',
    serverAdminPassword: '',
    ftpServerName: '',
    ftpServerAccount: '',
    wpLoginId: '',
    wpLoginPassword: '',
    otherLoginId: '',
    otherLoginPassword: ''
  },
})

export default store